config/routes.rb
Churchof::Application.routes.draw do

  

  resources :updates

  get "church_admin_panel/index"
  get "need_poster_panel/index"
  get "need_leader_panel/index"
  get "impact_panel/index"
  get "validation_partner_panel/index"
  get "organization_resource_validation_partner_panel/index"
  get "resource_partner_panel/index"
  get "user_panel/index"
  get "user_panel/new"
  get "user_panel/create"
  get "users/index"
  get "users_controller/index"
  post "needs/create_charge"
  post "needs/set_is_public"
  post "needs/set_in_progress_and_public"
  post "users/agree_to_need_poster_agreement"
  post "users/agree_to_need_leader_agreement"
  post "users/agree_to_church_admin_agreement"
  post "users/add_user_as_pending_need_poster"
  post "users/add_user_as_pending_need_leader"
  post "users/add_user_as_pending_church_admin"
  post "users/add_user_as_resource_partner"
  post "users/add_user_as_full_rosm_member"
  post "users/remove_user_as_full_rosm_member"
  post "resources/take_over_management"
  post "users/remove_user_as_resource_partner"
  get '/beta' => 'pages#beta'
  get '/contribution_terms' => 'pages#contribution_terms'
  get '/volunteering_terms' => 'pages#volunteering_terms'
  get '/skills_list' => 'pages#skills_list'
  get '/contribution_succeeded' => 'pages#contribution_succeeded'
  get '/contribution_failed' => 'pages#contribution_failed'
  get '/contribution_succeeded_account_invite' => 'pages#contribution_succeeded_account_invite'
  get "omniauth_callbacks/stripe_connect"

  devise_for :users#, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
  end

  resources :activities, only: [:create]

  resources :logs

  resources :about

  resources :match_campaigns
  resources :match_contributions

  resources :users # Not sure if this is ok to do with Devise also.

  resources :skills
  resources :organizations

  resources :resources do
    resources :resource_flags
    resources :resource_events
  end

  resources :organization_roles

  resources :needs do
    resources :contributions
    resources :time_contributions
    resources :expenses
    resources :updates
  end

  resources :initiatives do
    resources :initiative_metrics
  end

  resources :demographics

  get 'feed', to: 'needs#index', as: :feed

  root :to => 'needs#index'

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :resources
    end
  end

end

app/models/initiative_metric.rb
class Datapoint
  include ActiveModel::Serializers::JSON

  attr_accessor :year, :periodName, :value

  # def attributes=(hash)
  #   hash.each do |key, value|
  #     send("#{key}=", value)
  #   end
  # end

  # def attributes
  #   instance_values
  # end
end



class InitiativeMetric < ActiveRecord::Base

	require 'rest_client'
	require 'json'

	belongs_to :initiative



	def get_data_for_this_metric
		response = RestClient.post "http://api.bls.gov/publicAPI/v1/timeseries/data/", { 'seriesid' => ['LAUMT213046000000003'], 'startyear' => '2013', 'endyear' => '2014' }.to_json, :content_type => :json, :accept => :json
		hash = JSON.parse response

    datapoints = Array.new
    datapoints_two = Array.new
    hash['Results']['series'][0]['data'].each do |stuff|
      Rails.logger.info stuff['period']
      datapoint = Datapoint.new
      datapoint.year = stuff['year']
      datapoint.periodName = stuff['periodName']
      datapoint.value = stuff['value']
      datapoints << datapoint
      datapoints_two << [DateTime.new(stuff['year'].to_i,self.get_month_int(stuff['periodName']),1).to_time.utc.to_i, stuff['value']]
    end
    response
    datapoints_two
	end



  def get_month_int(month_short)
    month_int = 0
    if month_short == 'January'
      month_int = 1
    elsif month_short == 'February'
      month_int = 2
    elsif month_short == 'March'
      month_int = 3
    elsif month_short == 'April'
      month_int = 4
    elsif month_short == 'May'
      month_int = 5
    elsif month_short == 'June'
      month_int = 6
    elsif month_short == 'July'
      month_int = 7
    elsif month_short == 'August'
      month_int = 8
    elsif month_short == 'September'
      month_int = 9
    elsif month_short == 'October'
      month_int = 10
    elsif month_short == 'November'
      month_int = 11
    elsif month_short == 'December'
      month_int = 12
    else
      month_int = 1
    end
  end




end

app/controllers/initiative_metrics_controller.rb
class InitiativeMetricsController < ApplicationController
  load_and_authorize_resource
  before_action :set_initiative, only: [:new, :edit, :create, :index]
  before_action :set_initiative_metric, only: [:show, :edit, :update, :destroy]

  # GET /initiative_metrics
  # GET /initiative_metrics.json
  def index
    @initiative_metrics = InitiativeMetric.all
  end

  # GET /initiative_metrics/1
  # GET /initiative_metrics/1.json
  def show
  end

  # GET /initiative_metrics/new
  def new
    @initiative_metric = @initiative.initiative_metrics.new
  end

  # GET /initiative_metrics/1/edit
  def edit
  end

  # POST /initiative_metrics
  # POST /initiative_metrics.json
  def create
    @initiative_metric = @initiative.initiative_metrics.new(initiative_metric_params)

    respond_to do |format|
      if @initiative_metric.save
        format.html { redirect_to [@initiative, @initiative_metric], notice: 'Initiative metric was successfully created.' }
        format.json { render action: 'show', status: :created, location: @initiative_metric }
      else
        format.html { render action: 'new' }
        format.json { render json: [@initiative, @initiative_metric].errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /initiative_metrics/1
  # PATCH/PUT /initiative_metrics/1.json
  def update
    respond_to do |format|
      if @initiative_metric.update(initiative_metric_params)
        format.html { redirect_to [@initiative_metric.initiative, @initiative_metric], notice: 'Initiative metric was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: [@initiative_metric.initiative, @initiative_metric].errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /initiative_metrics/1
  # DELETE /initiative_metrics/1.json
  def destroy
    @initiative_metric.destroy
    respond_to do |format|
      format.html { redirect_to initiative_initiative_metrics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_initiative
      @initiative = Initiative.find(params[:initiative_id])
    end

    def set_initiative_metric
      @initiative_metric = InitiativeMetric.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def initiative_metric_params
      params.require(:initiative_metric).permit(:title)
    end
end

app/helpers/initiative_metrics_helper.rb
module InitiativeMetricsHelper
end

app/views/initiative_metrics/_form.html.erb
<%= simple_form_for [@initiative, @initiative_metric] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>
  
  <%= f.input :title %>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/initiative_metrics/edit.html.erb
<h1>Editing initiative_metric for <%= @initiative_metric.initiative.title %></h1>

<%= render 'form' %>

<%= link_to 'Show', [@initiative, @initiative_metric] %> |
<%= link_to 'Back', initiative_initiative_metrics_path %>

app/views/initiative_metrics/index.html.erb
<h1>Listing initiative_metrics for <%= @initiative.title %></h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @initiative_metrics.each do |initiative_metric| %>
      <tr>
        <td><%= initiative_metric.title %></td>
        <td><%= link_to 'Show', [@initiative, initiative_metric] %></td>
        <td><%= link_to 'Edit', edit_initiative_initiative_metric_path(initiative_metric.initiative ,initiative_metric) %></td>
        <td><%= link_to 'Destroy', [@initiative, initiative_metric], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Initiative metric', new_initiative_initiative_metric_path %>

app/views/initiative_metrics/new.html.erb
<h1>New initiative_metric for <%= @initiative.title %></h1>

<%= render 'form' %>

<%= link_to 'Back', initiative_initiative_metrics_path %>

app/views/initiative_metrics/show.html.erb
<h1>Initiative Metric for <%= @initiative_metric.initiative.title %></h1>

<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_initiative_initiative_metric_path(@initiative_metric.initiative, @initiative_metric) %> |
<%= link_to 'Back', initiative_initiative_metrics_path %>