config/routes.rb
Churchof::Application.routes.draw do

  

  resources :updates

  get "church_admin_panel/index"
  get "need_poster_panel/index"
  get "need_leader_panel/index"
  get "impact_panel/index"
  get "validation_partner_panel/index"
  get "organization_resource_validation_partner_panel/index"
  get "resource_partner_panel/index"
  get "user_panel/index"
  get "user_panel/new"
  get "user_panel/create"
  get "users/index"
  get "users_controller/index"
  post "needs/create_charge"
  post "needs/set_is_public"
  post "needs/set_in_progress_and_public"
  post "users/agree_to_need_poster_agreement"
  post "users/agree_to_need_leader_agreement"
  post "users/agree_to_church_admin_agreement"
  post "users/add_user_as_pending_need_poster"
  post "users/add_user_as_pending_need_leader"
  post "users/add_user_as_pending_church_admin"
  post "users/add_user_as_resource_partner"
  post "users/add_user_as_full_rosm_member"
  post "users/remove_user_as_full_rosm_member"
  post "resources/take_over_management"
  post "users/remove_user_as_resource_partner"
  get '/beta' => 'pages#beta'
  get '/contribution_terms' => 'pages#contribution_terms'
  get '/volunteering_terms' => 'pages#volunteering_terms'
  get '/skills_list' => 'pages#skills_list'
  get '/contribution_succeeded' => 'pages#contribution_succeeded'
  get '/contribution_failed' => 'pages#contribution_failed'
  get '/contribution_succeeded_account_invite' => 'pages#contribution_succeeded_account_invite'
  get "omniauth_callbacks/stripe_connect"

  devise_for :users#, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
  end

  resources :activities, only: [:create]

  resources :logs

  resources :about

  resources :match_campaigns
  resources :match_contributions

  resources :users # Not sure if this is ok to do with Devise also.

  resources :skills
  resources :organizations

  resources :resources do
    resources :resource_flags
    resources :resource_events
  end

  resources :organization_roles

  resources :needs do
    resources :contributions
    resources :time_contributions
    resources :expenses
    resources :updates
  end

  resources :initiatives do
    resources :initiative_metrics
  end

  resources :demographics

  get 'feed', to: 'needs#index', as: :feed

  root :to => 'needs#index'

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :resources
    end
  end

end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController
  load_and_authorize_resource
  before_action :set_need, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update]

  def set_is_public
    @need = Need.find(params["need"]["id"])

    authorize! :set_is_public, @need
    # Should only be able to set if its in progress so the archived version stays the same.
    if @need.need_stage_value == 2
      if params["need"]["is_public"] == "false"
        if @need.contributions.succeded.not_reimbursed.count == 0
          @need.is_public = params["need"]["is_public"]
          @need.save

          redirect_to "/church_admin_panel/index?selected=admin_in_progress", notice: 'Need was successfully updated.'
        else
          redirect_to "/church_admin_panel/index?selected=admin_in_progress", alert: 'Need was not updated because people have already given to it.'
        end
      else
        @need.is_public = params["need"]["is_public"]
        @need.save
        #
          redirect_to "/church_admin_panel/index?selected=admin_in_progress", notice: 'Need was successfully updated.'
      end
    end

  end


  def set_in_progress_and_public
    @need = Need.find(params["need"]["id"])
    @need.need_stage = :admin_in_progress
    @need.is_public = true
    @need.save
    redirect_to "/church_admin_panel/index?selected=admin_in_progress", notice: 'Need was successfully updated.'
  end


  # def record_usage
  #   logger.debug "Would record that activity here"
  # end

  # def filtered
  #   puts "Hello Mel"
  #   respond_to :js
  # end

  def create_charge
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Rails Stripe customer',
      :currency    => 'usd'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to root_path
  end

  # GET /needs
  # GET /needs.json
  def index
    if params[:selected_skills].present?
      skill_name = params[:selected_skills]
      @needs = Need.public.in_progress.joins(:skills).where("skills.name LIKE ?", skill_name).uniq.reverse
      @completed_needs = Need.public.completed.reverse

    else
      @needs = Need.public.in_progress.reverse
      # will only show completed need when not sorting...
      @completed_needs = Need.public.completed.reverse
    end

    @needs = @needs.select(&:completion_goal_date).sort_by(&:completion_goal_date) + @needs.reject(&:completion_goal_date)
    @completed_needs = @completed_needs.select(&:date_marked_completed).sort_by(&:date_marked_completed).reverse

    @skills = Skill.all

    skills_represented = Array.new
    @needs.each do |need|

      need.skills.each do |skill|
        skills_represented << skill
      end
      
    end
    @skills_represented = skills_represented.uniq

    @current_active_campaign = nil
    if MatchCampaign.current_active_campaign
      @current_active_campaign = MatchCampaign.current_active_campaign
    end
    
    @hash = Gmaps4rails.build_markers(@needs) do |need, marker|
      if need.shows_real_location_publically
        marker.lat need.latitude
        marker.lng need.longitude
      else
        marker.lat need.approx_latitude
        marker.lng need.approx_longitude
      end
      marker.infowindow need.title

      # marker.picture({
      #   :url    => "http://www.clker.com/cliparts/3/v/I/F/6/V/light-blue-circle-md.png",
      #   :width  => "32",
      #   :height => "32"
      # })
      marker.shadow({
      anchor: [2,22],
      url: '',
      width: 29,
      height: 22 })
      # This should use the path helper.
      marker.json({ title: need.title, image_url: need.skills.first ? need.skills.first.icon_url : '', custom_infowindow: "<a href='needs/#{need.id}'> #{Sanitize.clean(need.title_public)} </a>" })
    end

    # respond_to :html, :js

    respond_to do |format|
      format.html
      format.js
  end

  end

  # GET /needs/1
  # GET /needs/1.json
  def show
    @expense = Expense.new
    @needs = Need.where(id: params[:id])


    @current_active_campaign = nil
    if MatchCampaign.current_active_campaign
      @current_active_campaign = MatchCampaign.current_active_campaign
    end


    @hash = Gmaps4rails.build_markers(@needs) do |need, marker|
      if need.shows_real_location_publically
        marker.lat need.latitude
        marker.lng need.longitude
      else
        marker.lat need.approx_latitude
        marker.lng need.approx_longitude
      end
      marker.infowindow need.title

      # marker.picture({
      #   :url    => "http://www.clker.com/cliparts/3/v/I/F/6/V/light-blue-circle-md.png",
      #   :width  => "32",
      #   :height => "32"
      # })
      marker.shadow({
      anchor: [2,22],
      url: '',
      width: 29,
      height: 22 })
      # This should use the path helper.
      marker.json({ title: need.title, image_url: if need.skills.first then need.skills.first.icon_url else '' end})
    end

# if has appropriate role for the need
    if user_signed_in?
      if current_user == @need.user_church_admin || current_user == @need.user_need_leader
        begin
          url = "https://www.rosmky.org/secure/api/api.php?option=displayRequestsXML&FirstName=#{@need.first_name}&LastName=#{@need.last_name}&SSN=#{@need.last_four_ssn}&Key=#{ENV['ROSM_KEY']}"
          @rosm_results = Hash.from_xml(open(url).read)
        rescue
          puts "Error #{$!}"
          @rosm_results = Hash.new
        ensure 
        end
      end
    end
  end

  # GET /needs/new
  def new
    @need = Need.new
  end

  # GET /needs/1/edit
  def edit
  end

  # POST /needs
  # POST /needs.json
  def create
    @need = current_user.needs_posted_by.new(need_params)

    respond_to do |format|
      if @need.save
        format.html { redirect_to @need, notice: 'Need was successfully created.' }
        # format.json { render action: 'show', status: :created, location: @need }
      else
        format.html { render action: 'new' }
        # format.json { render json: @need.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /needs/1
  # PATCH/PUT /needs/1.json
  def update
    respond_to do |format|
      if @need.update(need_params)
        format.html { redirect_to @need, notice: 'Need was successfully updated.' }
        # format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        # format.json { render json: @need.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /needs/1
  # DELETE /needs/1.json
  def destroy
    @need.destroy
    respond_to do |format|
      format.html { redirect_to needs_url }
      # format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_need
      @need = Need.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def need_params
      params.require(:need).permit! #This is bad... #(:skill_tokens, :shows_real_location_publically, :id, :full_street_address, :recipient_size, :frequency_type, :recipient_contribution, :date_of_birth, :latitude, :longitude, :leader, :is_public, :first_name, :last_name, :last_four_ssn, :street_address, :drivers_license, :age, :gender, :title_public, :description_public, :need_stage, :title, :description, :user_id_posted_by, :user_id_church_admin)
    end
end

app/helpers/needs_helper.rb
module NeedsHelper
end

app/views/needs/_completed_need.html.erb
  <div class="need-container ">
    <div class="inner-content">


   <div class="row">
      <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">

        <h2 class="need-title">
          <%= link_to need.title_public, need %>
        </h2>

        <h4 class="need-title">
          Completed <%= time_ago_in_words(need.date_marked_completed) %> ago.
        </h4>

      </div>



      </div>


              <% if need.skills_count > 0 %>
        <div class="row need-details">

                <div class="skills col-xs-12 col-sm-6">
                  <ul class="skills-list">

                    <% need.skills.each do |skill| %>
                      <li class="skill-tag">
                        <span class="skill-icon">
                          <%= image_tag(skill.icon_url) %>
                        </span>
                        <%= skill.name %>
                      </li>
                                    <% end %>

                  </ul>
                </div>
                        </div>

              <% end %>



      <% if need.updates.count > 0 %>
        <% if need.updates.count == 1 %>
          <h3><%= need.updates.count %> Public Update</h3>
        <% else %>
          <h3><%= need.updates.count %> Public Updates</h3>
        <% end %>
      <% end %>

      <% need.updates.each do |update| %>
        <div class="public-update-bar" data-toggle="modal" data-target="#PublicUpdateModal<%= update.id%>">
          <span class="record-count"><%= update.title %></span>
<!--           This should only show up for the right people
 -->
          <span class="details"><%= time_ago_in_words(update.created_at) %> ago</span>
        </div>
      <% end %>



    </div>



<!-- need.volunteer_date_passed
 -->

</div>

app/views/needs/_form.html.erb
  <!-- jQuery is used only for this example; it isn't required to use Stripe -->

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>

<%= javascript_include_tag "jquery.tokeninput.js" %>
<%= stylesheet_link_tag "token-input-facebook.css" %>

<script>

$(document).ready(function () {
    updateSkills();
    function updateSkills(){
        $.ajax({
        url: '/skills.json',
        type: "GET",
        dataType: 'json',
        success: function(data) {
          skillsArray = data;
          $('.token-input-token-facebook').each(function(){
            $(this).addClass('custom');
            var skillText = $(this).find('p').text();
            for (i=0; i < skillsArray.length; i++){
              if(skillsArray[i].name == skillText){
                $(this).find('> p').html('<span class="skill-icon"><img src="' + skillsArray[i].icon_url + '"></span>' + skillsArray[i].name)
              }
            };
          });
        }
      });
    };

    $("#need_skill_tokens").tokenInput("/skills.json", {
      crossDomain: false,
      onAdd: function(item){
        updateSkills();
      },
      preventDuplicates: "true",
      theme: "facebook",
      prePopulate: $("#need_skill_tokens").data("pre")
    });
});

</script>
<%= simple_nested_form_for(@need, html: {class: "form-horizontal need-form"}) do |f| %>
  <div class="form-divider">
    <div class="col-xs-12">
      <% if @need.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@need.errors.count, "error") %> prohibited this need from being saved:</h2>
          <ul>
            <% @need.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
    </div>
    <div class="col-xs-12 col-sm-6">
      <div class="public-label">Public</div>
      <div class="inner-content">
        <div class="public-fields">
          <p class="form-instructions">Please title and describe the need:</p>
          <%= f.input :title_public, label: "Public Title" %>
          <%= f.input :description_public, label: "Public Description" %>
        </div>
        <div class="lone-field">
          <%= f.input :recipient_size, :as => :radio_buttons, :default  => "Unknown", label: "Recipient Size" %>
        </div>
        <div class="lone-field">
          <%= f.input :frequency_type, :as => :radio_buttons, :default  => "Unknown", label: "Frequency"  %>
        </div>
        <div class="lone-field">
          <%= f.input :full_street_address, label: "Full Street Address" %>
        </div>
        <div class="lone-field">
          <%= f.input :shows_real_location_publically, label: "Show Real Location Publicly", class: "public-checkbox" %>
        </div>
        <div class="lone-field ">
          <%= f.input :user_id_church_admin, label: "Church Admin", collection: User.with_role(:church_admin), label_method: :full_name %>
        </div>
        <div class="lone-field ">
          <%= f.input :organization_to_give_to_id, label: "Organization to Recieve Money", collection: Organization.all_orgs_able_to_give_to, label_method: :title %>
        </div>
        Dont see the organization you want the money to go to on this list? As of March, 2015, organizations must now link a bank account inorder to recieve funds. You can link a bank account to an organization you are connected to here: <%= link_to "Finances Panel", organization_roles_path %>

        <div class="lone-field">
          <%= f.input :user_id_need_leader, label: "Leader", collection: User.with_role(:need_leader), label_method: :full_name %>
        </div>


        <div class="lone-field">
          <%= f.input :completion_goal_date, :include_blank => true, label: "Goal Date" %>



        </div>


        <div class="lone-field">

          <%= link_to "Full list of Skills", skills_list_path, target: "_blank" %>

          
          <h4><%= f.label :skill_tokens, "Skills" %></h4>
          <%= f.text_field :skill_tokens, "data-pre" => @need.skills.map(&:attributes).to_json %>
        </div>
      </div>
    </div>

    <div class="col-xs-12 col-sm-6" id="private-block">
      <div class="private-label">Private</div>
        <div class="inner-content">
          <div class="private-fields">
            <p class="form-instructions">Please title and describe the need:</p>
            <%= f.input :title, label: "Private Title" %>
            <%= f.input :description, label: "Private Description" %>
          </div>
          <div class="form-for-individuals">
            <div class="field-pair">
              <%= f.input :first_name, label: "First Name"%>
            </div>
            <div class="field-pair">
              <%= f.input :last_name, label: "Last Name" %>
            </div>
            <div class="field-pair">
              <%= f.input :last_four_ssn, label: "Last 4 SSN" %>
            </div>
            <div class="field-pair">
              <%= f.input :street_address, label: "Street Address" %>
            </div>
            <div class="field-group-3">
              <%= f.input :drivers_license, label: "Driver's License" %>
            </div>
            <div class="field-group-3">
              <%= f.input :date_of_birth, label: "DOB (mm/dd/yy)" %>
            </div>
            <div class="field-group-3">
              <%= f.input :gender, label: "Gender" %>
            </div>
            <div class="lone-field">
              <%= f.input :recipient_contribution, label: "Recipient's Contribution" %>
            </div>
          </div>
        </div>
    </div>

    <div class="grey-form col-xs-12">
      <div class="secondary-form-inner-content">


        <h4>Volunteers</h4>
            <div class="field-group-3">
              <%= f.input :volunteersNeededCount, label: "Number of Volunteers Needed" %>
            </div>
            <div class="field-group-3">
              <%= f.input :additionalVolunteersSignedUpCount, label: "Number of Additional Volunteers" %>
            </div>
            <div class="field-group-3">
              <%= f.input :volunteerTime, :include_blank => true, label: "Volunteer Time" %>
            </div>
            <div class="field-group-3">
              <%= f.input :volunteerLocation, label: "Volunteer Location" %>
            </div>
            <div class="field-group-3">
              <%= f.input :volunteerDescription, label: "Volunteer Description" %>
            </div>


            <br>
                        <br>
                        <br>


        <h4>Expenses</h4>

          <%= f.fields_for :expenses do |expense| %>
            <div class="grid-needs">
              <div class="grid-block">
                  <div class="grid-col">
                    <%= expense.input :title %>
                  </div>
                  <div class="grid-col">
                    <%= expense.input :description %>
                  </div>
                  <div class="grid-col">
                    <%= expense.input :documentation %>
                  </div>
                  <div class="grid-col">
                    <%= expense.input :amount %>
                  </div>
                  <div class="grid-col remove-expense"><%= expense.link_to_remove "Remove" %></div>
                </div>
            </div>
        <% end %>
        <%= f.link_to_add "+ Add an Expense", :expenses %>

                                <br>
                        <br>

        <div class="public-updates-block">

          <h4>Public Updates</h4>

          <%= f.fields_for :updates do |update| %>
          <div class="update-wrapper">
            <div class="update-inner-content">
              <div class="form-inputs">
                <div class="field-pair">
                  <%= update.input :title %>
                </div>
                <div class="field-pair">
                  <%= update.input :content, :class => "long-content-textarea" %>
                </div>
              </div>

              <div class="images-block">
                <%= update.fields_for :images do |image| %>
                  <div class="image-field">
                    <div class="field-group-30">
                      <%= image.label "Select Your Image:" %>
                      <%= image.file_field :image %>
                    </div>
                    <div class="field-group-70">
                      <%= image.input :caption %>
                    </div>
                  <%= image.link_to_remove "Remove Image" %>
                  </div>
                <% end %>

                <p><%= update.link_to_add "Add an image", :images %></p>
              </div>
              <%= update.link_to_remove "Remove Update", :class => "remove-update" %>
            </div>
            </div>
          <% end %>

          <p><%= f.link_to_add "+ Add a Public Update", :updates %></p>
        </div>
      </div>
    </div>
  </div>

  <div class="form-actions submit-new-need">
    <%= f.button :submit, "Submit" %>
  </div>
<% end %>

<script>
  $(document).on('ready', function(){
    $('.form-for-individuals').hide();
    $('ul.token-input-list-facebook').addClass('custom');
    if($('#need_recipient_size_individual').attr('checked')){
      $('.form-for-individuals').show();
    }
    $('.radio_buttons').each(function(){
      if($(this).attr('checked') == "checked"){
        $(this).parent().addClass('selected');
      }
    });

    $('.need_recipient_size .radio_buttons').on('click', function(){
      $('.need_recipient_size .radio').each(function(){
        $(this).removeClass('selected');
      })
      $(this).parent().addClass('selected');
      if($(this).val() == "individual"){
        $('.form-for-individuals').show();
      }else{
        $('.form-for-individuals').hide();
      }
    });

    $('.need_frequency_type .radio_buttons').on('click', function(){
      $('.need_frequency_type .radio').each(function(){
        $(this).removeClass('selected');
      })
      $(this).parent().addClass('selected');
    });
  });
</script>

app/views/needs/_need.html.erb
  <div class="need-container">
    <div class="inner-content">


   <div class="row">
      <div class="col-xs-12 col-sm-9">

        <h2 class="need-title">
          <%= link_to need.title_public, need %>
        </h2>

      </div>


        <% if need.date_public_posted %>
              <div class="col-xs-12 col-sm-3" id="time-block-on-index">


                <% if need.need_stage_value == 3 %>
                  <div class="time-block time-green">
                    <div class="time-remaining">
                      Completed
                    </div>
                    <div class="time-posted">
                      <% if need.date_public_posted %>
                        posted: <%= time_ago_in_words(need.date_public_posted) %> ago
                      <% else %>
                        not posted publicly
                      <% end %>
                    </div>
                  </div>

                <% elsif need.percent_raised == 100 %>

                  <div class="time-block time-green">
                    <div class="time-remaining">
                      Fully Funded
                    </div>
                    <div class="time-posted">
                      <% if need.date_public_posted %>
                        posted: <%= time_ago_in_words(need.date_public_posted) %> ago
                      <% else %>
                        not posted publicly
                      <% end %>
                    </div>
                  </div>

                <% else %>


                  <% if need.completion_goal_date %>
                    <% if need.completion_goal_date > Time.current %>
                      <% if need.completion_goal_date > Time.current + 1.days %>
                        <div class="time-block time-green">
                          <div class="time-remaining">
                            <%= time_ago_in_words(need.completion_goal_date) %> left
                          </div>
                          <div class="time-posted">
                            <% if need.date_public_posted %>
                              posted: <%= time_ago_in_words(need.date_public_posted) %> ago
                            <% end %>
                          </div>
                        </div>
                      <% else %>
                        <div class="time-block time-orange">
                          <div class="time-remaining">
                            <%= time_ago_in_words(need.completion_goal_date) %> left
                          </div>
                          <div class="time-posted">
                            <% if need.date_public_posted %>
                              posted: <%= time_ago_in_words(need.date_public_posted) %> ago
                            <% end %>
                          </div>
                        </div>
                      <% end %>
                    <% else %>
                      <div class="time-block time-red">
                        <div class="time-remaining">
                          <%= time_ago_in_words(need.completion_goal_date) %> past goal
                        </div>
                        <div class="time-posted">
                          <% if need.date_public_posted %>
                            posted: <%= time_ago_in_words(need.date_public_posted) %> ago
                          <% end %>
                        </div>
                      </div>
                    <% end %>
                  <% else %>
                    <div class="time-block time-blue">
                      <div class="time-remaining">
                        No Goal Date
                      </div>
                      <div class="time-posted">
                        <% if need.date_public_posted %>
                          posted: <%= time_ago_in_words(need.date_public_posted) %> ago
                        <% end %>
                      </div>
                    </div>
                  <% end %>
              <% end %>
        <% end %>

      </div>
      </div>

      <div class="need-description">
        <p><%= need.description_public %></p>
        <div class="row need-details">

          <% if need.expenses.count > 0 %>
            <div class="expenses col-xs-12 col-sm-6">
              <h3>Expenses</h3>
                <div class="expenses-bar">
                  <span class="progress-bar" style="width:<%= need.percent_raised %>%"><span class="matched-bar" style="width:<%= need.percent_raised_from_matched_contributions %>%"></span></span>

                  

                  <span class="amount-raised"><%= humanized_money_with_symbol need.total_contributed %> / <%= humanized_money_with_symbol need.total_expenses %></span>
                </div>

                <br>
                <% if need.total_people_who_have_given == 1 %>
                  <%= need.total_people_who_have_given %> person has contributed.
                <% else %>
                  <%= need.total_people_who_have_given %> people have contributed.
                <% end %>

            </div>
          <% end %>

          <% if need.total_needed_volunteers > 0 %>

          <div class="volunteers col-xs-12 col-sm-6">
            <h3>Volunteers</h3>

            <div class="volunteers-bar">
              <span class="progress-bar" style="width:<%= need.percent_volunteers_secured %>%"></span>
              <span class="amount-raised"><%= need.total_volunteers %> / <%= need.total_needed_volunteers %></span>
            </div>
          </div>
          <% end %>

          <div class="skills col-xs-12 col-sm-6">
            <h3>Skills / Resources</h3>
            <ul class="skills-list">
              <% if need.skills_count > 0 %>
                <% need.skills.each do |skill| %>
                  <li class="skill-tag">
                    <span class="skill-icon">
                      <%= image_tag(skill.icon_url) %>
                    </span>
                    <%= skill.name %>
                  </li>
                <% end %>
              <% else %>
                No skills added yet.
              <% end %>
            </ul>
          </div>
        </div>
      </div>


    </div>



<!-- need.volunteer_date_passed
 -->

  <div class="need-button-block cf">
    <%= link_to 'Read More', need_path(need), :class => "need-btn-link full-width-btn" %>

      <% if need.should_accept_contributions %>
          <%= link_to 'Contribute', new_need_contribution_path(need), :class => "need-btn-link full-width-btn-green" %>
      <% end %>





    <% if need.should_accept_volunteers %>
      <% if user_signed_in? %>
        <% if need.time_contribution_for_user(current_user.id) %>
          <% if need.time_contribution_for_user(current_user.id).cancelled %>
            <%= link_to 'Volunteer', edit_need_time_contribution_path(need, need.time_contribution_for_user_id(current_user.id)), :class => "need-btn-link full-width-btn-purple" %>
          <%else%>
            <%= link_to 'Cancel Volunteering', edit_need_time_contribution_path(need, need.time_contribution_for_user_id(current_user.id)), :class => "need-btn-link full-width-btn-red" %>
          <% end %>
        <% else %>
          <%= link_to 'Volunteer', new_need_time_contribution_path(need), :class => "need-btn-link full-width-btn-purple" %>
        <% end %>
      <% else %>
        <%= link_to 'Volunteer', new_need_time_contribution_path(need), :class => "need-btn-link full-width-btn-purple" %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/needs/_needs_script.html.erb
<script>
  $(document).ready(function(){
    $('.need-button-block').each(function(){
      var className;
      var needButtonCount = $(this).find('.need-btn-link').length;
        if (needButtonCount == 1){
          className = "need-xs-12";
        }else if(needButtonCount == 2){
          className = "need-xs-6";
        }else if(needButtonCount == 3){
          className = "need-xs-4";
        }

      $(this).find('.need-btn-link').each(function(){
        $(this).addClass(className);
      });
    });
  })

</script>

app/views/needs/edit.html.erb
<div class="page-header-block">
  <div class="page-title">
  </div>
</div>

<div class="main-content">
  <div class="need-container edit">
    <%= render 'form' %>
  </div>
</div>

app/views/needs/index.js.erb
$("div.needs").html("<%=j render @needs %><%=j render 'needs_script' %>");
var map_hash = <%= raw @hash.to_json %>;
jQuery(function(){ buildNeedsMap(map_hash, true, false); });
// jQuery(function(){ replaceMap(map_hash); });

app/views/needs/new.html.erb
<%= link_to 'Back',  need_poster_panel_index_path %>

<div class="page-header-block">
  <div class="page-title">
    <h2>Post a Need</h2>
  </div>
</div>

<div class="main-content main-bg">
  <%= render 'form' %>
</div>