config/routes.rb
Churchof::Application.routes.draw do

  

  resources :updates

  get "church_admin_panel/index"
  get "need_poster_panel/index"
  get "need_leader_panel/index"
  get "impact_panel/index"
  get "validation_partner_panel/index"
  get "organization_resource_validation_partner_panel/index"
  get "resource_partner_panel/index"
  get "user_panel/index"
  get "user_panel/new"
  get "user_panel/create"
  get "users/index"
  get "users_controller/index"
  post "needs/create_charge"
  post "needs/set_is_public"
  post "needs/set_in_progress_and_public"
  post "users/agree_to_need_poster_agreement"
  post "users/agree_to_need_leader_agreement"
  post "users/agree_to_church_admin_agreement"
  post "users/add_user_as_pending_need_poster"
  post "users/add_user_as_pending_need_leader"
  post "users/add_user_as_pending_church_admin"
  post "users/add_user_as_resource_partner"
  post "users/add_user_as_full_rosm_member"
  post "users/remove_user_as_full_rosm_member"
  post "resources/take_over_management"
  post "users/remove_user_as_resource_partner"
  get '/beta' => 'pages#beta'
  get '/contribution_terms' => 'pages#contribution_terms'
  get '/volunteering_terms' => 'pages#volunteering_terms'
  get '/skills_list' => 'pages#skills_list'
  get '/contribution_succeeded' => 'pages#contribution_succeeded'
  get '/contribution_failed' => 'pages#contribution_failed'
  get '/contribution_succeeded_account_invite' => 'pages#contribution_succeeded_account_invite'
  get "omniauth_callbacks/stripe_connect"

  devise_for :users#, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
  end

  resources :activities, only: [:create]

  resources :logs

  resources :about

  resources :match_campaigns
  resources :match_contributions

  resources :users # Not sure if this is ok to do with Devise also.

  resources :skills
  resources :organizations

  resources :resources do
    resources :resource_flags
    resources :resource_events
  end

  resources :organization_roles

  resources :needs do
    resources :contributions
    resources :time_contributions
    resources :expenses
    resources :updates
  end

  resources :initiatives do
    resources :initiative_metrics
  end

  resources :demographics

  get 'feed', to: 'needs#index', as: :feed

  root :to => 'needs#index'

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :resources
    end
  end

end

app/views/resources/_form.html.erb
<%= simple_nested_form_for @resource do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this expense from being saved:</h2>
      <ul>
      <% @resource.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

      <div class="field-pair">
        <%= f.input :title %>
      </div>
      <div class="field-pair">
        <%= f.input :description %>
      </div>
      <div class="field-pair">
        <%= f.input :website %>
      </div>
      <div class="field-pair">
        <%= f.input :contact_phone %>
      </div>
      <div class="field-pair">
        <%= f.input :contact_email %>
      </div>

      <%= f.input :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>

      <div class="field-pair">
        <%= f.input :availability_status %>
      </div>
      <div class="field-pair">
        <%= f.input :status %>
      </div>
      <div class="field-pair">
        <%= f.input :address %>
      </div>

      <div class="field-pair">
        <%= f.input :organization_id, collection: Organization.all.order('title'), label_method: :title %>
      </div>
        <div>
          <%= f.association :skills, as: :check_boxes %>
        </div>


        <div class="lone-field">
          <%= f.association :demographics, as: :check_boxes %>
        </div>


      <div class="field-pair">
        <%= f.input :public_status %>
      </div>
      <br>
      <br>







          <h4>Events</h4>

          <%= f.fields_for :resource_events do |resource_event| %>
          <div class="update-wrapper">
            <div class="update-inner-content">
              <div class="form-inputs">
                <div class="field-pair">
                  <%= resource_event.select_recurring :schedule %>
                </div>
                <div class="field-pair">
                  <%= resource_event.input :start_time, :ampm => true %>
                </div>
                <div class="field-pair">
                  <%= resource_event.input :end_time, :ampm => true %>
                </div>
              </div>
              <%= resource_event.link_to_remove "Remove Event" %>
            </div>
            </div>
          <% end %>

          <p><%= f.link_to_add "+ Add an Event", :resource_events %></p>
        </div>










<br>
      <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/resources/_map.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>

<div id="custom_style" class="custom_style">
  <script type="text/javascript">
    //jQuery(function(){ buildMap(<%=raw @hash.to_json %>); });

    // handler = Gmaps.build('Google');
    // handler.buildMap({ 
    // provider: {
    //   zoom:      13,
    //     center:    new google.maps.LatLng(38.040584, -84.503716),
    //   mapTypeId: google.maps.MapTypeId.ROADMAP,
    //     styles:    [{'featureType':'water','stylers':[{'visibility':'on'},{'color':'#acbcc9'}]},{'featureType':'landscape','stylers':[{'color':'#f2e5d4'}]},{'featureType':'road.highway','elementType':'geometry','stylers':[{'color':'#c5c6c6'}]},{'featureType':'road.arterial','elementType':'geometry','stylers':[{'color':'#e4d7c6'}]},{'featureType':'road.local','elementType':'geometry','stylers':[{'color':'#fbfaf7'}]},{'featureType':'poi.park','elementType':'geometry','stylers':[{'color':'#c5dac6'}]},{'featureType':'administrative','stylers':[{'visibility':'on'},{'lightness':33}]},{'featureType':'road'},{'featureType':'poi.park','elementType':'labels','stylers':[{'visibility':'on'},{'lightness':20}]},{},{'featureType':'road','stylers':[{'lightness':20}]}]
    // }, 
    // internal: {
    //   id: 'custom_style'}
    // }, 
    // function(){
    //   markers = handler.addMarkers(<%=raw @hash.to_json %>);
    //   //handler.bounds.extendWith(markers);
    //   //handler.fitMapToBounds();
    // });
  </script>
</div>

app/views/resources/_resource.html.erb
					<div class="needs main-content" id="needs-full-list">
					  <div class="resource-container">
					    <div class="inner-content">
					   		<div class="row">
					      	<div class="col-xs-12 col-sm-12">
										<h2 class="resource-title"><%= resource.title %>
											<br>
											<% if resource.availability_status %>
													<% if resource.availability_status.fully_available? %>
														<% if resource.status.length > 0 %>
															<font color="69c773">(Fully Available - <%= resource.status %>)</font></h2>
														<% else %>
													  		<font color="69c773">(Fully Available)</font></h2>
														<% end %>
											  	<% elsif resource.availability_status.mostly_available? %>
														<% if resource.status.length > 0 %>
															<font color="69c773">(Mostly Available - <%= resource.status %>)</font></h2>
														<% else %>
													  		<font color="69c773">(Mostly Available)</font></h2>
														<% end %>
											  	<% elsif resource.availability_status.mostly_not_available? %>
												  		<% if resource.status.length > 0 %>
															<font color="FF8A3B">(Nearing Limit - <%= resource.status %>)</font></h2>
															<% else %>
													  		<font color="FF8A3B">(Nearing Limit)</font></h2>
															<% end %>
											  	<% elsif resource.availability_status.not_available? %>
												  	<% if resource.status.length > 0 %>
															<font color="e06c69">(Not Available - <%= resource.status %>)</font></h2>
														<% else %>
													  		<font color="e06c69">(Not Available)</font></h2>
														<% end %>
													<% end %>

											<% else %>
												<% if resource.status.length > 0 %>
													<font color="58A1EB">(<%= resource.status %>)</font></h2>
												<% end %>
											<% end %>
										</div>

										<div class="skills col-xs-12 col-sm-12">

					            <ul class="demographics-list">
					              <% if resource.demographics.count > 0 %>
					              This resource is intended for the following demographics: <br><br>
					                <% resource.demographics.each do |demographic| %>
					                  <li class="demographic-tag">
					                    <span class="demographic-icon">
					                      <%= image_tag(demographic.icon_url) %>
					                    </span>
					                    <%= demographic.title %>
					                  </li>
					                <% end %>
					              <% end %>
					            </ul>




					            <ul class="skills-list">
					              <% if resource.skills.count > 0 %>
					                <% resource.skills.each do |skill| %>
					                  <li class="skill-tag">
					                    <span class="skill-icon">
					                      <%= image_tag(skill.icon_url) %>
					                    </span>
					                    <%= skill.name %>
					                  </li>
					                <% end %>
					              <% else %>
					                No skills added yet.
					              <% end %>
					            </ul>
								    </div>

										<% if resource.flagged %>
										    <div class="resource-alert-red">
										      This resource has been flagged enough times to be removed. You are only seeing it because of your role. It is not visible to the general public.
										    </div>
										<% end %>

										<% if !resource.public_status.available_to_public? %>
										    <div class="resource-alert-orange">
												This resource is not public. You are only seeing it because of your role. It is not visible to the general public.
											</div>
										<% end %>

										<% if resource.current_percentage_flagged > 10.0 %>
											<div class="resource-alert-red">
												This resource has been flagged by <%= resource.current_percentage_flagged %>% of Church Admins.
											</div>
										<% end %>


										<% if resource.description.length > 0 %>
									      <div class="resource-description col-xs-12 col-sm-12">
													<%= resource.description %>
									      </div>
									  <% end %>

										<% if resource.resource_events.count > 0 %>
									      <div class="field-icon">
									        <%= image_tag("https://s3.amazonaws.com/church_of/assets/resource_assets/728-clock%402x.png") %>
									        <% begin %>
									        	<span class="field-description">
															<% resource.resource_events.each do |resource_event| %>
																<%= resource_event.schedule_ice_cube.to_s %>:
																<%= resource_event.start_time.strftime('%I:%M %p') %> - 
																<%= resource_event.end_time.strftime('%I:%M %p') %>.
															<% end %>
														</span>
									      	<% rescue %>
									    	<% end %>
									      </div>
								    <% end %>

										<% if resource.contact_email.length > 0 %>
									      <div class="field-icon">
									        <%= image_tag("https://s3.amazonaws.com/church_of/assets/resource_assets/730-envelope%402x.png") %>
											<span class="field-description">
											<%= resource.contact_email %>
											</span>
									      </div>
								    <% end %>

										<% if resource.website.length > 0 %>
									      <div class="field-icon">
									        <%= image_tag("https://s3.amazonaws.com/church_of/assets/resource_assets/715-globe%402x.png") %>
											<span class="field-description">
									        <%= resource.website %>
											</span>
									      </div>
								    <% end %>

										<% if resource.contact_phone.length > 0 %>
									      <div class="field-icon">
									        <%= image_tag("https://s3.amazonaws.com/church_of/assets/resource_assets/735-phone%402x.png") %>
											<span class="field-description">
									        <%= resource.contact_phone %>
											</span>
									      </div>
								    <% end %>

										<% if resource.address.length > 0 %>
									      <div class="field-icon">
									        <%= image_tag("https://s3.amazonaws.com/church_of/assets/resource_assets/722-location-pin%402x.png") %>
											<span class="field-description">
									        <%= resource.address %>
											</span>
									      </div>
									    <% end %>

									    <% if resource.user %>
											<% if resource.is_verified %>
											    <div class="field-icon">
												    <%= image_tag("https://s3.amazonaws.com/church_of/assets/resource_assets/check_on.png") %>
													<span class="field-description">
														Listing managed by <%= resource.user.full_name %> from <%=resource.organization.title %>
													</span>
											    </div>
											<% else %>
												<div class="field-icon">
													<%= image_tag("https://s3.amazonaws.com/church_of/assets/resource_assets/check_off.png") %>
													<span class="field-description">
														Listing managed by <%= resource.user.full_name %> from Church of Lexington
													</span>
												</div>
											<% end %>
										<% end %>

								    <div class="last-updated">
								      	Last Updated: <%= time_ago_in_words(resource.updated_at) %> ago <a href="mailto:support@church-of.com" target="_top">Suggest an Edit</a>

									   <% if user_signed_in? %>
									   	<% if current_user.has_role? :church_admin %>
									       <% if resource.resource_flag_for_user(current_user.id) %>
									         <% if resource.resource_flag_for_user(current_user.id).flagged %>
									           <%= link_to 'Edit Flag', edit_resource_resource_flag_path(resource, resource.resource_flag_for_user_id(current_user.id)), :class => "flag-button" %>
									         <%else%>
									           <%= link_to 'Flag', edit_resource_resource_flag_path(resource, resource.resource_flag_for_user_id(current_user.id)), :class => "flag-button" %>
											<% end %>
									       <% else %>
									         <%= link_to 'Flag', new_resource_resource_flag_path(resource), :class => "flag-button" %>
									       <% end %>
									     <% end %>
									   <% end %>
								    </div>
									</div>
								</div>
							</div>
						</div>

app/views/resources/_resources_by_organization.html.erb
<% if params[:selected_skill] == "Free Meals" %>
	<div class="notice-well">
		<div class="notice-image-2">
		</div>
		<div class="notice-text">
			Looking for Free Meals? Have an iPhone? Download our app to find the closest next available free meal!
		</div>
	</div>
<% end %>

<% if @users.count > 0 %>
	<% if @users.count == 1 %>
		<div class="notice-well">
			<div class="notice-image-1">
			</div>
			<div class="notice-text">
				There is 1 user who has the “<%= params[:selected_skill] %>” skill. Post a Need and they will be notified.
			</div>
		</div>
	<% else %>
		<div class="notice-well">
			<div class="notice-image-1">
			</div>
			<div class="notice-text">
				There are <%= @users.count %> users who have the “<%= params[:selected_skill] %>” skill. Post a Need and they will all be notified.
			</div>
		</div>
	<% end %>
<% end %>


<% @organizations.each do |organization| %>
		<br>
		<b><h2>
		<%= link_to organization.title, organization %>

			<% if organization.is_verified %>
				<span class="org-verified-icon"><%= image_tag("https://s3.amazonaws.com/church_of/assets/resource_assets/check_on.png") %></span>
			<% end %>
		</h2></b>

		<% @resources.each do |resource| %>
			<% if resource.organization == organization %>
				<%= render 'resource', resource: resource %>
			<% end %>
		<% end %>
<% end %>


 <% if @resources.count == 0 %>
	<br>
    <br>
    <h2>No Programs found. Try selecting different search parameters.</h2>
 <% end %>

<%= paginate @organizations %>

app/views/resources/_skills_select.html.erb
<script type="text/javascript">


$(document).ready(function () {

    $("#skills_list").on("change", function () {
      var initiativeSelectedValue = ""
      var skillSelectedValue = ""
      var demographicSelectedValue = ""
      var searchValue = ""
      $('#needs-full-list').html();
      initiativeSelectedValue = $('#initiatives_list option:selected').val();
      skillSelectedValue = $('#skills_list option:selected').val();
      demographicSelectedValue = $('#demographics_list option:selected').val();
      searchValue = $('#search_box').val();
      $("div.loading").show();
      $("div.resources").html("");
      $.ajax({
          type: "GET",
          url: "/resources",
          data: {
            selected_initiative: initiativeSelectedValue,
            selected_skill: skillSelectedValue,
            selected_demographic: demographicSelectedValue,
            search_value: searchValue
          },
          dataType: "script",
          success: function(data) {
            if ($('.resource-container').length == 0){
              $('#needs-full-list').html('There are no resources yet listed under this skill set.');
            }
          }
        });
    });

     });


</script>


    <select id="skills_list" class="skill-select" <%=params[:selected_initiative].present? ? "enabled" : "disabled"%> >
      <option value="">All Categories</option>
      <%- @skills_to_show.each do | skill | %>
      	<% if params[:selected_skill].present? %>
      		<% if params[:selected_skill] == skill.name %>
      			<% if params[:selected_initiative].present? %>
			        <option data-tag="#{skill.name}" selected>
			          <%= skill.name %>
			        </option>
		        <% else %>
			        <option data-tag="#{skill.name}">
			          <%= skill.name %>
			        </option>
		        <% end %>
      		<% else %>
		        <option data-tag="#{skill.name}">
		          <%= skill.name %>
		        </option>
      		<% end %>
      	<% else %>
    			<option data-tag="#{skill.name}">
	          <%= skill.name %>
	        </option>
      	<% end %>
      <% end %>
    </select>

app/views/resources/_small_map.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js' type='text/javascript'></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script>

<div id="custom_style" style='width: 100%; min-height: 240px;'>
  <script type="text/javascript">
    //jQuery(function(){ buildMap(<%=raw @hash.to_json %>); });

    // handler = Gmaps.build('Google');
    // handler.buildMap({ 
    // provider: {
    //   zoom:      13,
    //     center:    new google.maps.LatLng(38.040584, -84.503716),
    //   mapTypeId: google.maps.MapTypeId.ROADMAP,
    //     styles:    [{'featureType':'water','stylers':[{'visibility':'on'},{'color':'#acbcc9'}]},{'featureType':'landscape','stylers':[{'color':'#f2e5d4'}]},{'featureType':'road.highway','elementType':'geometry','stylers':[{'color':'#c5c6c6'}]},{'featureType':'road.arterial','elementType':'geometry','stylers':[{'color':'#e4d7c6'}]},{'featureType':'road.local','elementType':'geometry','stylers':[{'color':'#fbfaf7'}]},{'featureType':'poi.park','elementType':'geometry','stylers':[{'color':'#c5dac6'}]},{'featureType':'administrative','stylers':[{'visibility':'on'},{'lightness':33}]},{'featureType':'road'},{'featureType':'poi.park','elementType':'labels','stylers':[{'visibility':'on'},{'lightness':20}]},{},{'featureType':'road','stylers':[{'lightness':20}]}]
    // }, 
    // internal: {
    //   id: 'custom_style'}
    // }, 
    // function(){
    //   markers = handler.addMarkers(<%=raw @hash.to_json %>);
    //   //handler.bounds.extendWith(markers);
    //   //handler.fitMapToBounds();
    // });
  </script>
</div>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form' %>

app/views/resources/index.html.erb
<% content_for :banner do %>

<span class="show-on-xs">
    <div class="banner">
      <div class="container">
        <div class="banner-btn-mobile">
          <div class="banner-btn-text">
            <%= link_to "Read our Vision", about_index_path %>
          </div>
        </div>
      </div>
    </div>

</span>
<span class="hide-on-xs">
    <div class="banner">
      <div class="container">
        <div class="banner-text">
          We’re aiming to unite the Church through crowd-sourced service.
        </div>
        <div class="banner-btn">
          <div class="banner-btn-text">
            <%= link_to "Read our Vision", about_index_path %>
          </div>
        </div>
      </div>
    </div>

</span>
<% end %>


<% content_for :head do %>
  <script src="https://s3.amazonaws.com/churchof/jquery.isotope.min.js"></script>
  <script src="https://s3.amazonaws.com/churchof/imagesloaded-min.js"></script>
  <script type="text/javascript">

 jQuery(function(){ buildResourcesMap(map_hash, true, false); });
   </script>

<% end %>


<script type="text/javascript">


$(document).ready(function () {


    $("#initiatives_list").on("change", function () {
      var initiativeSelectedValue = ""
      var skillSelectedValue = ""
      var demographicSelectedValue = ""
      var searchValue = ""
      $('#needs-full-list').html();
      initiativeSelectedValue = $('#initiatives_list option:selected').val();
      demographicSelectedValue = $('#demographics_list option:selected').val();
      searchValue = $('#search_box').val();
      $("div.loading").show();
      $("div.resources").html("");
      $.ajax({
          type: "GET",
          url: "/resources",
          data: {
            selected_initiative: initiativeSelectedValue,
            selected_skill: skillSelectedValue,
            selected_demographic: demographicSelectedValue,
            search_value: searchValue
          },
          dataType: "script",
          success: function(data) {
            if ($('.resource-container').length == 0){
              $('#needs-full-list').html('There are no resources yet listed under this skill set.');
            }
          }
        });
    });


    $("#demographics_list").on("change", function () {
      var initiativeSelectedValue = ""
      var skillSelectedValue = ""
      var demographicSelectedValue = ""
      var searchValue = ""
      $('#needs-full-list').html();
      initiativeSelectedValue = $('#initiatives_list option:selected').val();
      skillSelectedValue = $('#skills_list option:selected').val();
      demographicSelectedValue = $('#demographics_list option:selected').val();
      searchValue = $('#search_box').val();
      $("div.loading").show();
      $("div.resources").html("");
      $.ajax({
          type: "GET",
          url: "/resources",
          data: {
            selected_initiative: initiativeSelectedValue,
            selected_skill: skillSelectedValue,
            selected_demographic: demographicSelectedValue,
            search_value: searchValue
          },
          dataType: "script",
          success: function(data) {
            if ($('.resource-container').length == 0){
              $('#needs-full-list').html('There are no resources yet listed under this skill set.');
            }
          }
        });
    });


var delay = (function(){
  var timer = 0;
  return function(callback, ms){
    clearTimeout (timer);
    timer = setTimeout(callback, ms);
  };
})();


$('input').keydown(function() {
    delay(function(){


      var initiativeSelectedValue = ""
      var skillSelectedValue = ""
      var demographicSelectedValue = ""
      var searchValue = ""
      $('#needs-full-list').html();
      initiativeSelectedValue = $('#initiatives_list option:selected').val();
      skillSelectedValue = $('#skills_list option:selected').val();
      demographicSelectedValue = $('#demographics_list option:selected').val();
      searchValue = $('#search_box').val();
      $("div.loading").show();
      $("div.resources").html("");
      $.ajax({
          type: "GET",
          url: "/resources",
          data: {
            selected_initiative: initiativeSelectedValue,
            selected_skill: skillSelectedValue,
            selected_demographic: demographicSelectedValue,
            search_value: searchValue
          },
          dataType: "script",
          success: function(data) {
            if ($('.resource-container').length == 0){
              $('#needs-full-list').html('There are no resources yet listed under this skill set.');
            }
          }
        });










    }, 1000 );
});



 });


  </script>




<% content_for :map do %>
  <script>
    var map_hash = <%= raw @hash.to_json %>;
  </script>
  <%= render 'map' %>
<% end %>


<div class="page-header-block">
  <h1 class="need-category-title">Programs</h1>

  <br>

  <div class="initiatives-filter">
    <select id="initiatives_list" class="initiative-select">
        <option value="">All Initiatives</option>
      <%- Initiative.all.each do | initiative | %>
        <option data-tag="#{initiative.title}">
          <%= initiative.title %>
        </div>
      <% end %>
    </select>
  </div>

  <div class="categories-filter">

     <%= render 'skills_select' %>

  </div>




<input class="search-box" id= "search_box" type="text" size="25" value="" placeholder="Search">

</div>





<div class="loading" id="loading" style="display:none; margin-left:50%; margin-top:100px;">
<div id="spinnerContainer" class="spinner" style="width:100%;height:100px;">
</div>
<script src="Scripts/Spin.js" type="text/javascript"></script>
<script type="text/javascript">
    var opts = {
      lines: 13, // The number of lines to draw
      length: 7, // The length of each line
      width: 4, // The line thickness
      radius: 10, // The radius of the inner circle
      corners: 1, // Corner roundness (0..1)
      rotate: 0, // The rotation offset
      color: '#000', // #rgb or #rrggbb
      speed: 1, // Rounds per second
      trail: 60, // Afterglow percentage
      shadow: false, // Whether to render a shadow
      hwaccel: false, // Whether to use hardware acceleration
      className: 'spinner', // The CSS class to assign to the spinner
      zIndex: 2e9, // The z-index (defaults to 2000000000)
    };
    var target = document.getElementById('spinnerContainer');
    var spinner = new Spinner(opts).spin(target);
</script>

</div>

<div class="resources" id="resources">
   <%= render 'resources_by_organization' %>
</div>

app/views/resources/index.js.erb
$("div.categories-filter").html("<%=j render 'skills_select' %>");
$("div.resources").html("<%=j render 'resources_by_organization' %>");
$("div.loading").hide();
var map_hash = <%= raw @hash.to_json %>;
jQuery(function(){ buildResourcesMap(map_hash, true, false); });

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form' %>