config/routes.rb
Churchof::Application.routes.draw do

  

  resources :updates

  get "church_admin_panel/index"
  get "need_poster_panel/index"
  get "need_leader_panel/index"
  get "impact_panel/index"
  get "validation_partner_panel/index"
  get "organization_resource_validation_partner_panel/index"
  get "resource_partner_panel/index"
  get "user_panel/index"
  get "user_panel/new"
  get "user_panel/create"
  get "users/index"
  get "users_controller/index"
  post "needs/create_charge"
  post "needs/set_is_public"
  post "needs/set_in_progress_and_public"
  post "users/agree_to_need_poster_agreement"
  post "users/agree_to_need_leader_agreement"
  post "users/agree_to_church_admin_agreement"
  post "users/add_user_as_pending_need_poster"
  post "users/add_user_as_pending_need_leader"
  post "users/add_user_as_pending_church_admin"
  post "users/add_user_as_resource_partner"
  post "users/add_user_as_full_rosm_member"
  post "users/remove_user_as_full_rosm_member"
  post "resources/take_over_management"
  post "users/remove_user_as_resource_partner"
  get '/beta' => 'pages#beta'
  get '/contribution_terms' => 'pages#contribution_terms'
  get '/volunteering_terms' => 'pages#volunteering_terms'
  get '/skills_list' => 'pages#skills_list'
  get '/contribution_succeeded' => 'pages#contribution_succeeded'
  get '/contribution_failed' => 'pages#contribution_failed'
  get '/contribution_succeeded_account_invite' => 'pages#contribution_succeeded_account_invite'
  get "omniauth_callbacks/stripe_connect"

  devise_for :users#, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }

  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
  end

  resources :activities, only: [:create]

  resources :logs

  resources :about

  resources :match_campaigns
  resources :match_contributions

  resources :users # Not sure if this is ok to do with Devise also.

  resources :skills
  resources :organizations

  resources :resources do
    resources :resource_flags
    resources :resource_events
  end

  resources :organization_roles

  resources :needs do
    resources :contributions
    resources :time_contributions
    resources :expenses
    resources :updates
  end

  resources :initiatives do
    resources :initiative_metrics
  end

  resources :demographics

  get 'feed', to: 'needs#index', as: :feed

  root :to => 'needs#index'

  namespace :api, :defaults => {:format => :json} do
    namespace :v1 do
      resources :resources
    end
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController

  skip_authorization_check

  def index
	end

end

app/helpers/about_helper.rb
module AboutHelper
end

app/views/about/index.html.erb
<%= stylesheet_link_tag "application", :media => "all" %>
<%= stylesheet_link_tag params[:controller] %>

<%= content_for :hero_block do %>  

<span class="hide-on-xs">
	<div class="main-title"> Uniting the Church through crowd-sourced service. </div>
	<div class="main-sentence"> As a Christian body, we are called to be one. Unfortunately, divisions often keep us from rallying around our joint mission. The "Church of Lexington” platform is a practical step forward. Let’s all pitch in on something we agree on by being the "hands and feet" to our city. </div>
	<div class="menu-background-people">
	</div>
</span>

<span class="show-on-xs">
	<div class="main-mobile-title"> Uniting the Church through crowd-sourced service. </div>
	<div class="main-mobile-sentence"> As a Christian body, we are called to be one. Unfortunately, divisions often keep us from rallying around our joint mission. The "Church of Lexington” platform is a practical step forward. Let’s all pitch in on something we agree on by being the "hands and feet" to our city. </div>
	<div class="menu-mobile-people">
	</div>
</span>

<span class="hide-on-xs">
	<div class="menu-line">
		<div class="menu-circle">
			<ul class="nav nav-pills">
			 	<li class="active"><a href="#users" data-toggle="tab">For Users</a></li>
				<li><a href="#churches" data-toggle="tab">For Churches</a></li>
				<li><a href="#nonprofits" data-toggle="tab">For Non-Profits</a></li>
			</ul>
		</div>
	</div>
</span>

<span class="hide-on-xs">
    <div id="my-tab-content" class="tab-content">
        <div class="tab-pane active" id="users">
            
            <div class= "side-image-1"> </div>
						<div class="left-title">You are uniquely equipped to meet your city’s Needs.</div>
						<div class="left-sentence">Chances are, you’re good at something.  Whether that’s wielding a hammer or a pen, managing people or managing things. When you add skills to your profile you’ll automatically be notified when the Church is made aware of a need that matches your capabilities.<br><br><%= link_to "Manage my Skills", edit_user_registration_path, :class => "about-link" %></div>
						
						<div class= "side-image-2"> </div>
						<div class="right-title">See the Needs around you in real-time, all the time.</div>
						<div class="right-sentence">Churches and Non-Profits post needs in the community so we can all pitch in. Needs are screened and approved by local churches, so you can trust that each one is valid.<br><br><%= link_to "See Current Needs", needs_path, :class => "about-link" %></div>
						
						<div class= "side-image-3"> </div>
						<div class="left-title">Give to specific Needs and get specific feedback.</div>
						<div class="left-sentence">There’s something human about helping each other out. It connects and unifies us. Too often, when we give, we are unable to see the direct impact. With the "Church of Lexington" platform, 100% of your donation goes straight to the organiztion meeting the need through the local Church. (The organization itself will cover the credit card fees). You’ll then be kept up-to-date as the need is met.<br><br><%= link_to "Track My Impact", impact_panel_index_path, :class => "about-link" %></div>
						
						<div class= "side-image-4"> </div>
						<div class="right-title">Help guide the Church to use its resources responsibly.</div>
						<div class="right-sentence">The Church is not a building, it’s a group of people. We should all play a part in helping that group act with integrity. Where are the Church's resources going? Where should they be going? Can we be more responsible with what we've been given? The "Church of Lexington" provides a transparent platform for new initiatives.<br><br><div class="about-link">Initiative Progress Coming Soon</div></div>
        </div>
        <div class="tab-pane" id="churches">
            
            <div class= "side-image-5"> </div>
						<div class="left-title">Allow your congregation to be a part of the story.</div>
						<div class="left-sentence">There's a certain joy that comes with generosity. Those in charge of allocating the Church's resources get to see this on a daily basis. Its harder, though, for those that give the money to see the direct impact. Transparency allows the congregation members to be a part of the story and in turn encourages them to continue giving to the good work the Church is doing.<br><br><%= link_to "Post a Need", new_need_path, :class => "about-link" %></div>
						
						<div class= "side-image-6"> </div>
						<div class="right-title">List all the good work you are doing in one place.</div>
						<div class="right-sentence">Your profile page will show all of the Needs you are currently meeting. Its a great place to keep your congregation involved in what your church is doing. It also gives space for people to jump in and be a part.<br><br><%= link_to "Check Out Profile Pages", organizations_path, :class => "about-link" %></div>
						
						<div class= "side-image-7"> </div>
						<div class="left-title">A united Church.</div>
						<div class="left-sentence">We all agree we should be working together more... but where do we start? By posting all of the opportunities in one place we'll have an unprecendented chance to cross polenate as we seek to serve the city. Any church who agrees to the oldest of ecumenical creeds (the Apostle's Creed) is able to help manage the platform.<br><br><%= link_to "See Churches Involved", organizations_path, :class => "about-link" %></div>
						
						<div class= "side-image-8"> </div>
						<div class="right-title">Tools & Data to serve more efficiently.</div>
						<div class="right-sentence">We took all the printed resource guides and brought them into the 21st century. Each group can manage their own resources and set availability statuses. No more wasted phone calls to groups who are "out of resources for the rest of the month." We also give churches access to ROSM's Database to make the most informed decision possible.<br><br><%= link_to "See Resources", resources_path, :class => "about-link" %></div>
        </div>
        <div class="tab-pane" id="nonprofits">
            
            <div class= "side-image-9"> </div>
						<div class="left-title">Partner with the Church in the good work you are doing.</div>
						<div class="left-sentence">Non-profits do a lot of creative and innovative work in our city. More often than not, these groups have goals aligned with the Church. Both groups are on the front lines; its a natural fit.<br><br><%= link_to "Post a Need", new_need_path, :class => "about-link" %></div>
						
						<div class= "side-image-10"> </div>
						<div class="right-title">Add your resources to an ever-growing resource guide.</div>
						<div class="right-sentence">We took all the printed resource guides and brought them into the 21st century. Each group can manage their own resources and set availability statuses. Out of a certain resource for the month? Have a lot of extra resources this month? Mark it as such on your profile so churches can reach out to you accordingly.<br><br><%= link_to "See Resources", resources_path, :class => "about-link" %></div>
        </div>
    </div>
<br>
    <%= link_to "Sign Up", register_path, :class => "sign-up-link" %>
</div>

</span>



<span class="show-on-xs">

	<div class="mobile-line">
		<div class="mobile-circle">
			<div class="mobile-menu-object">
				For Users
			</div>
		</div>
	</div>

	<div class="mobile-title-right">You are uniquely equipped to meet your city’s Needs.</div>
  <div class= "mobile-image-1"> </div>
	<div class="mobile-sentence-right">Chances are, you’re good at something.  Whether that’s wielding a hammer or a pen, managing people or managing things. When you add skills to your profile you’ll automatically be notified when the Church is made aware of a need that matches your capabilities.<br><br><%= link_to "Manage my Skills", edit_user_registration_path, :class => "about-link" %></div>

	<div class="mobile-title-left">See the Needs around you in real-time, all the time.</div>
  <div class= "mobile-image-2"> </div>
	<div class="mobile-sentence-left">Churches and Non-Profits post needs in the community so we can all pitch in. Needs are screened and approved by local churches, so you can trust that each one is valid.<br><br><%= link_to "See Current Needs", needs_path, :class => "about-link" %></div>

	<div class="mobile-title-right">Give to specific Needs and get specific feedback.</div>
  <div class= "mobile-image-3"> </div>
	<div class="mobile-sentence-right">There’s something human about helping each other out. It connects and unifies us. Too often, when we give, we are unable to see the direct impact. With the "Church of Lexington" platform, 100% of your donation goes straight to the organiztion meeting the need through the local Church. (The organization itself will cover the credit card fees). You’ll then be kept up-to-date as the need is met.<br><br><%= link_to "Track My Impact", impact_panel_index_path, :class => "about-link" %></div>

	<div class="mobile-title-left">Help guide the Church to use its resources responsibly.</div>
  <div class= "mobile-image-4"> </div>
	<div class="mobile-sentence-left">The Church is not a building, it’s a group of people. We should all play a part in helping that group act with integrity. Where are the Church's resources going? Where should they be going? Can we be more responsible with what we've been given? The "Church of Lexington" provides a transparent platform for new initiatives.<br><br><div class="about-link">Initiative Progress Coming Soon</div></div>

	<div class="mobile-line">
		<div class="mobile-circle">
			<div class="mobile-menu-object">
				For Churches
			</div>
		</div>
	</div>

	<div class="mobile-title-right">Allow your congregation to be a part of the story.</div>
  <div class= "mobile-image-5"> </div>
	<div class="mobile-sentence-right">There's a certain joy that comes with generosity. Those in charge of allocating the Church's resources get to see this on a daily basis. Its harder, though, for those that give the money to see the direct impact. Transparency allows the congregation members to be a part of the story and in turn encourages them to continue giving to the good work the Church is doing.<br><br><%= link_to "Post a Need", new_need_path, :class => "about-link" %></div>

	<div class="mobile-title-left">List all the good work you are doing in one place.</div>
  <div class= "mobile-image-6"> </div>
	<div class="mobile-sentence-left">Your profile page will show all of the Needs you are currently meeting. Its a great place to keep your congregation involved in what your church is doing. It also gives space for people to jump in and be a part.<br><br><%= link_to "Check Out Profile Pages", organizations_path, :class => "about-link" %></div>

	<div class="mobile-title-right">A united Church.</div>
  <div class= "mobile-image-7"> </div>
	<div class="mobile-sentence-right">We all agree we should be working together more... but where do we start? By posting all of the opportunities in one place we'll have an unprecendented chance to cross polenate as we seek to serve the city. Any church who agrees to the oldest of ecumenical creeds (the Apostle's Creed) is able to help manage the platform.<br><br><%= link_to "See Churches Involved", organizations_path, :class => "about-link" %></div>

	<div class="mobile-title-left">Tools & Data to serve more efficiently.</div>
  <div class= "mobile-image-8"> </div>
	<div class="mobile-sentence-left">We took all the printed resource guides and brought them into the 21st century. Each group can manage their own resources and set availability statuses. No more wasted phone calls to groups who are "out of resources for the rest of the month." We also give churches access to ROSM's Database to make the most informed decision possible.<br><br><%= link_to "See Resources", resources_path, :class => "about-link" %></div>

	<div class="mobile-line">
		<div class="mobile-circle">
			<div class="mobile-menu-object">
				For Non-Profits
			</div>
		</div>
	</div>

	<div class="mobile-title-right">Partner with the Church in the good work you are doing.</div>
  <div class= "mobile-image-9"> </div>
	<div class="mobile-sentence-right">Non-profits do a lot of creative and innovative work in our city. More often than not, these groups have goals aligned with the Church. Both groups are on the front lines; its a natural fit.<br><br><%= link_to "Post a Need", new_need_path, :class => "about-link" %></div>

	<div class="mobile-title-left">Add your resources to an ever-growing resource guide.</div>
  <div class= "mobile-image-10"> </div>
	<div class="mobile-sentence-left">We took all the printed resource guides and brought them into the 21st century. Each group can manage their own resources and set availability statuses. Out of a certain resource for the month? Have a lot of extra resources this month? Mark it as such on your profile so churches can reach out to you accordingly.<br><br><%= link_to "See Resources", resources_path, :class => "about-link" %></div>

    <%= link_to "Sign Up", register_path, :class => "sign-up-link-mobile" %></div>

</span>
<%end %>